### ISSUE TITLE
Errors in console if switch WME to Event Mode

### ISSUE THREAD

**Issue by madnut-ua** [WazeDev/WME-Route-Speeds-MapOMatic-Fork#1]
if switch WME to Event Mode, In loopWMERouteSpeeds() function the following call returns null (line 666):
`var tab = getId('sidepanel-routespeeds-tab');`
which causes script to fail with exceptions.

To fix this, the next line should check tab for null as well, e.g. like this:
`if (tab == null || tab === 'undefined') return;`

**Comment by justins83** [comment]
This is now fixed.
