### ISSUE TITLE
Always retrieve all routes.  Use dropdown to select how many to display.

### ISSUE THREAD

**Issue by mapomatic** [WazeDev/WME-Route-Speeds-MapOMatic-Fork#5]
Get rid of the Try More button.  Does nothing anymore.

When obtaining routes, cache the results.  Change the Alternatives option to something like:
Display [X] of 3 available routes

If user selects a different X, retrieve the results from the cache instead of going to the server.

**Comment by tonestertm** [comment]
I *believe*, when multiple routes are returned, all of them are already cached, we just need to expand internal handling for more than 5 routes.
