### ISSUE TITLE
Reduce the number of calls to the routing server

### ISSUE THREAD

**Issue by mapomatic** [WazeDev/WME-Route-Speeds-MapOMatic-Fork#6]
There are some times when the script automatically requests routes when an option is changed, and it probably shouldn't be.  Just needs a display update.  Some examples:

- Speed in mph
- Show cross-times through segments
- Disable script
- Hide labels
- Use routing order  (I think?)

**Comment by tonestertm** [comment]
Correct, 
* Use Routing Order does not require a new request
Also
* Real-time traffic (which is nearly useless, anyway: only shows actual traffic from about the last hour.)

**Comment by mapomatic** [comment]
Fixed, thanks to @Harmonious4
